project_id = "uwzjdosvirwzgbiouzcd"

[functions.upload-zen-track]
verify_jwt = false

[functions.generate-recording-metadata]
verify_jwt = true

[functions.analyze-tone]
verify_jwt = true

[functions.rewrite-thought]
verify_jwt = true
